import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0B1E47',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  logoWrap: { marginBottom: 24, alignItems: 'center' },
  logo: {
    fontSize: 36,
    fontWeight: '700',
    color: '#14B8A6',
    letterSpacing: 2,
    textShadowColor: '#000000',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 6,
  },
  subtitle: { color: '#9aa4b2', marginTop: 6 },
  form: {
    width: '100%',
    backgroundColor: '#1E3A8A',
    padding: 18,
    borderRadius: 12,
    shadowColor: '#000',
  },
  input: {
    backgroundColor: '#2C2C34',
    padding: 12,
    borderRadius: 8,
    color: '#fff',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#14B8A6',
  },
  passwordContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C34',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#14B8A6',
    marginBottom: 12,
    paddingRight: 10,
  },
  toggleText: { color: '#fff', fontSize: 18, paddingHorizontal: 6 },
  roleRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  roleBtn: {
    flex: 1,
    padding: 10,
    borderRadius: 8,
    alignItems: 'center',
    marginHorizontal: 6,
    borderWidth: 1,
    borderColor: '#1f2937',
  },
  roleBtnActive: { backgroundColor: '#10B981', borderColor: '#065f46' },
  roleTextActive: { color: '#fff', fontWeight: '600', letterSpacing: 1 },
  roleBtnActiveAdmin: { backgroundColor: '#3B82F6', borderColor: '#1D4ED8' },
  roleTextActiveAdmin: { color: '#fff', fontWeight: '600', letterSpacing: 1 },
  roleText: { color: '#cbd5e1' },
  button: {
    marginTop: 6,
    backgroundColor: '#F59E0B',
    padding: 12,
    borderRadius: 10,
    alignItems: 'center',
  },
  buttonText: { color: '#fff', fontWeight: '600' },
  error: { color: '#fd5151ff', marginBottom: 6, textAlign: 'center', fontWeight: '600' },
  signupText: { marginTop: 14, color: '#D1D5DB', textAlign: 'center' },
  hint: { marginTop: 10, color: '#D1D5DB', fontSize: 12, textAlign: 'center' },
});